### ISSUE TITLE
Will there be a signed version of the driver?

### ISSUE THREAD

**Issue by onguarde** [Slion/TrackPointDriver#1]
bcdedit /set testsigning on

An error has occurred setting the element data.
The value is protected by Secure Boot policy and cannot be modified or deleted.

**Comment by Slion** [comment]
I have the same issue on my company's PC. It would be awesome if the driver could be signed but I'm currently putting zero effort towards that goal. Unless people donate massively or someone sponsors it somehow it seems unlikely to ever happen. Even less so that I'm currently mostly working from home still.

**Comment by nefarius** [comment]
I think this can be closed? 😉

**Comment by Slion** [comment]
Indeed there is a signed version you can download from:
https://slions.net/resources/trackpoint-driver.12/
